[package]
name = "taskchampion-sync-server"
version = "0.4.1"
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "^1.3.0", features = ["serde", "v4"] }
actix-web = "^4.3.1"
anyhow = "1.0"
thiserror = "1.0"
futures = "^0.3.25"
serde = "^1.0.147"
serde_json = "^1.0"
clap = { version = "^4.3.0", features = ["string"] }
log = "^0.4.17"
env_logger = "^0.10.0"
rusqlite = { version = "0.29", features = ["bundled"] }
chrono = { version = "^0.4.22", features = ["serde"] }

[dev-dependencies]
actix-rt = "2"
tempfile = "3"
pretty_assertions = "1"
