version: '3'
services:
  test-fedora38:
    build:
        context: .
        dockerfile: test/docker/fedora38
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-fedora39:
    build:
        context: .
        dockerfile: test/docker/fedora39
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-ubuntu2004:
    build:
        context: .
        dockerfile: test/docker/ubuntu2004
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-ubuntu2204:
    build:
        context: .
        dockerfile: test/docker/ubuntu2204
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-debiantesting:
    build:
        context: .
        dockerfile: test/docker/debiantesting
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-opensuse:
    build:
        context: .
        dockerfile: test/docker/opensuse
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-arch:
    build:
        context: .
        dockerfile: test/docker/arch
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
